# change when set up in local
spring:
  datasource:
    #    jdbc:postgresql://<host>:<port>/<database>
    url: jdbc:postgresql://localhost:5432/osahaneat
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # none - not create in db if not exists
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG          # log request/response MVC
    org.springframework.security.web.FilterChainProxy: TRACE  # log thứ tự filter

jwt:
  privateKey: YMHSmjBxy968154aoc9c1Q4imkJd4hRwgs3fpkWNe/w=

fileUpload:
  rootPath: src/main/resources/static/images