server:
  port: 8080

spring:
  application:
    name: Solo-Leaf-app

  datasource: # database on render
    url: jdbc:postgresql://dpg-d44b5i2dbo4c73bo2flg-a.oregon-postgres.render.com:5432/solo_leaf_db_lzi5
    username: solo_leaf_db_lzi5_user
    password: vktPXzZDS2PdJLUubshFpu8gLtABcFLG
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # none - not create in db if not exists
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG          # log request/response MVC
    org.springframework.security.web.FilterChainProxy: TRACE  # log thứ tự filter

jwt:
  privateKey: YMHSmjBxy968154aoc9c1Q4imkJd4hRwgs3fpkWNe/w=

fileUpload:
  rootPath: src/main/resources/static/images
