server:
  port: ${PORT:8080}
  address: 0.0.0.0

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: Solo-Leaf-app

# ========= DEV (local, pgAdmin4) =========
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:osahaneat}?sslmode=${DB_SSLMODE:disable}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security.web.FilterChainProxy: TRACE

jwt:
  privateKey: ${JWT_PRIVATE_KEY:YMHSmjBxy968154aoc9c1Q4imkJd4hRwgs3fpkWNe/w=}

fileUpload:
  rootPath: ${FILE_UPLOAD_ROOT:src/main/resources/static/images}

# ========= PROD (Render) =========
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?sslmode=${DB_SSLMODE:require}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate   # muốn auto update thì đổi thành 'update'
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  level:
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.springframework.security.web.FilterChainProxy: INFO

jwt:
  privateKey: ${JWT_PRIVATE_KEY:YMHSmjBxy968154aoc9c1Q4imkJd4hRwgs3fpkWNe/w=}

fileUpload:
  # Trên Render: dùng thư mục tạm hoặc gắn Persistent Disk
  rootPath: ${FILE_UPLOAD_ROOT:/var/tmp/solo-leaf-uploads}